"""create_all_tables

Revision ID: 7f16e62b8bca
Revises: 
Create Date: 2026-03-29 13:34:13.414292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f16e62b8bca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("provider IN ('LOCAL', 'GOOGLE')", name='chk_users_provider'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('host_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('host_timezone', sa.String(length=50), nullable=False),
    sa.Column('slot_duration_mins', sa.Integer(), nullable=False),
    sa.Column('buffer_duration_mins', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('approval_type', sa.String(length=20), nullable=False),
    sa.Column('booking_open_days_ahead', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('booking_close_minutes_before', sa.Integer(), server_default=sa.text('120'), nullable=False),
    sa.Column('cancel_deadline_minutes_before', sa.Integer(), server_default=sa.text('1440'), nullable=False),
    sa.Column('max_active_bookings_per_user', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("approval_type IN ('AUTO', 'MANUAL')", name='chk_host_settings_approval_type'),
    sa.CheckConstraint("btrim(host_timezone) <> ''", name='chk_host_settings_host_timezone_not_blank'),
    sa.CheckConstraint("btrim(title) <> ''", name='chk_host_settings_title_not_blank'),
    sa.CheckConstraint("slug ~ '^[a-z0-9-]+$'", name='chk_host_settings_slug_format'),
    sa.CheckConstraint('booking_close_minutes_before >= 0', name='chk_host_settings_close_minutes_before'),
    sa.CheckConstraint('booking_open_days_ahead >= 0', name='chk_host_settings_open_days_ahead'),
    sa.CheckConstraint('buffer_duration_mins >= 0', name='chk_host_settings_buffer_duration'),
    sa.CheckConstraint('cancel_deadline_minutes_before >= 0', name='chk_host_settings_cancel_deadline'),
    sa.CheckConstraint('max_active_bookings_per_user >= 1', name='chk_host_settings_max_active_bookings'),
    sa.CheckConstraint('slot_duration_mins > 0', name='chk_host_settings_slot_duration'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_host_settings_slug')
    )
    op.create_index('idx_host_settings_host_id', 'host_settings', ['host_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('idx_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_table('schedule_overrides',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('host_setting_id', sa.UUID(), nullable=False),
    sa.Column('override_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('override_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("(override_type = 'DAY_OFF' AND start_time IS NULL AND end_time IS NULL) OR (override_type IN ('OPEN', 'BLOCK') AND start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)", name='chk_schedule_overrides_time_logic'),
    sa.CheckConstraint("override_type IN ('DAY_OFF', 'OPEN', 'BLOCK')", name='chk_schedule_overrides_type'),
    sa.ForeignKeyConstraint(['host_setting_id'], ['host_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_overrides_host_setting_date', 'schedule_overrides', ['host_setting_id', 'override_date'], unique=False)
    op.create_table('schedule_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('host_setting_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('effective_start_date', sa.Date(), nullable=True),
    sa.Column('effective_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("rule_type IN ('OPEN', 'BREAK')", name='chk_schedule_rules_rule_type'),
    sa.CheckConstraint('(effective_end_date IS NULL OR effective_start_date IS NULL OR effective_end_date >= effective_start_date)', name='chk_schedule_rules_effective_date_range'),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='chk_schedule_rules_day_of_week'),
    sa.CheckConstraint('end_time > start_time', name='chk_schedule_rules_time_range'),
    sa.ForeignKeyConstraint(['host_setting_id'], ['host_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_rules_host_setting_id', 'schedule_rules', ['host_setting_id'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('host_setting_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'BOOKED', 'BLOCKED')", name='chk_slots_status'),
    sa.CheckConstraint('end_time > start_time', name='chk_slots_time_range'),
    sa.ForeignKeyConstraint(['host_setting_id'], ['host_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_setting_id', 'start_time', name='uq_slots_host_setting_start_time')
    )
    op.create_index('idx_slots_host_setting_start_time_status', 'slots', ['host_setting_id', 'start_time', 'status'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('booker_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('request_message', sa.Text(), nullable=True),
    sa.Column('status_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'NO_SHOW', 'COMPLETED')", name='chk_bookings_status'),
    sa.ForeignKeyConstraint(['booker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booker_id', 'idempotency_key', name='uq_bookings_booker_idempotency')
    )
    op.create_index('idx_bookings_booker_created_at', 'bookings', ['booker_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_bookings_slot_id', 'bookings', ['slot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bookings_slot_id', table_name='bookings')
    op.drop_index('idx_bookings_booker_created_at', table_name='bookings', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('bookings')
    op.drop_index('idx_slots_host_setting_start_time_status', table_name='slots')
    op.drop_table('slots')
    op.drop_index('idx_schedule_rules_host_setting_id', table_name='schedule_rules')
    op.drop_table('schedule_rules')
    op.drop_index('idx_schedule_overrides_host_setting_date', table_name='schedule_overrides')
    op.drop_table('schedule_overrides')
    op.drop_index('idx_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('idx_host_settings_host_id', table_name='host_settings')
    op.drop_table('host_settings')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
