"""API error_code 문자열 상수 — docs/api_usecase.md 및 공통 규격과 맞춤."""


class ErrorCode:
    """클라이언트·로그에서 식별용 코드 (변경 시 API 문서 동기화)."""

    # 공통 / 인증
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    INVALID_TOKEN = "INVALID_TOKEN"
    INVALID_INPUT = "INVALID_INPUT"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    USER_INACTIVE = "USER_INACTIVE"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    EXPIRED_REFRESH_TOKEN = "EXPIRED_REFRESH_TOKEN"
    INVALID_AUTH_CODE = "INVALID_AUTH_CODE"
    OAUTH_LOGIN_FAILED = "OAUTH_LOGIN_FAILED"
    OAUTH_PROVIDER_ERROR = "OAUTH_PROVIDER_ERROR"
    HOST_ROLE_REQUIRED = "HOST_ROLE_REQUIRED"
    ADMIN_ROLE_REQUIRED = "ADMIN_ROLE_REQUIRED"
    PENDING_HOST_REQUEST_NOT_FOUND = "PENDING_HOST_REQUEST_NOT_FOUND"

    # 예약 페이지 / 슬롯
    BOOKING_PAGE_NOT_FOUND = "BOOKING_PAGE_NOT_FOUND"
    BOOKING_PAGE_INACTIVE = "BOOKING_PAGE_INACTIVE"
    INVALID_DATE_RANGE = "INVALID_DATE_RANGE"
    INVALID_DATE = "INVALID_DATE"
    SLOT_NOT_FOUND = "SLOT_NOT_FOUND"
    SLOT_NOT_OPEN = "SLOT_NOT_OPEN"
    SLOT_ALREADY_BOOKED = "SLOT_ALREADY_BOOKED"
    SLOT_ALREADY_HELD = "SLOT_ALREADY_HELD"
    HOLD_EXPIRED = "HOLD_EXPIRED"
    DUPLICATE_REQUEST = "DUPLICATE_REQUEST"
    POLICY_VIOLATION = "POLICY_VIOLATION"

    # 예약
    BOOKING_NOT_FOUND = "BOOKING_NOT_FOUND"
    INVALID_BOOKING_STATUS = "INVALID_BOOKING_STATUS"
    CANCELLATION_DEADLINE_PASSED = "CANCELLATION_DEADLINE_PASSED"

    # 호스트 설정
    HOST_SETTING_NOT_FOUND = "HOST_SETTING_NOT_FOUND"
    HOST_SETTING_HAS_BOOKINGS = "HOST_SETTING_HAS_BOOKINGS"
    SLUG_ALREADY_EXISTS = "SLUG_ALREADY_EXISTS"
    RULE_NOT_FOUND = "RULE_NOT_FOUND"
    OVERRIDE_NOT_FOUND = "OVERRIDE_NOT_FOUND"
    OVERLAPPING_RULE = "OVERLAPPING_RULE"
    OVERLAPPING_OVERRIDE = "OVERLAPPING_OVERRIDE"
    INVALID_TIME_RANGE = "INVALID_TIME_RANGE"
    INVALID_OVERRIDE_TYPE = "INVALID_OVERRIDE_TYPE"
    SLOT_NOT_BLOCKED = "SLOT_NOT_BLOCKED"

    # 내부
    INTERNAL_ERROR = "INTERNAL_ERROR"
